name: train-procgen
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pytorch=1.13.*
  - torchvision
  - pyyaml
  - pandas
  - matplotlib
  - tensorboard==2.5
  - tqdm
  - imageio[ffmpeg]
  - pip:
    - gym3
    - git+https://github.com/JacobPfau/procgenAISC